//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogCategory
    {
        public int ID { get; set; }
        public string BlogCategoryName { get; set; }
        public string BlogURL { get; set; }
        public int Level { get; set; }
        public int Rank { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescriptions { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public bool IsDelete { get; set; }
    }
}
