//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuEnglishName { get; set; }
        public string MenuURL { get; set; }
        public int Level { get; set; }
        public int Rank { get; set; }
        public string MenuImage { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public bool IsDelete { get; set; }
    }
}
