//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CubeTechWebEntities : DbContext
    {
        public CubeTechWebEntities()
            : base("name=CubeTechWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogCategory> BlogCategories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuType> MenuTypes { get; set; }
        public virtual DbSet<OurCustomer> OurCustomers { get; set; }
        public virtual DbSet<PageInfo> PageInfoes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductStandard> ProductStandards { get; set; }
        public virtual DbSet<ProductStandardDetail> ProductStandardDetails { get; set; }
        public virtual DbSet<ProductStandardValue> ProductStandardValues { get; set; }
        public virtual DbSet<ProductUpdateLog> ProductUpdateLogs { get; set; }
        public virtual DbSet<RecommendProduct> RecommendProducts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<StaticPage> StaticPages { get; set; }
        public virtual DbSet<StaticUrl> StaticUrls { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
