//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurCustomer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Info { get; set; }
        public string Website { get; set; }
        public string PhoneNumber { get; set; }
        public string Fanpage { get; set; }
        public string Project { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public bool IsDelete { get; set; }
    }
}
