//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageInfo
    {
        public int ID { get; set; }
        public string ShopName { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string FanPage { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescriptions { get; set; }
        public string SEOImage { get; set; }
    }
}
