//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductUpdateLog
    {
        public int ID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string BeforeUpdate { get; set; }
        public string UserUpdate { get; set; }
        public string ErrorMessage { get; set; }
    }
}
