//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string IDAndSize { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public decimal Price { get; set; }
        public decimal PriceSale { get; set; }
        public decimal PriceSale2 { get; set; }
        public bool IsMultipleStandard { get; set; }
        public string Standard1 { get; set; }
        public string Standard2 { get; set; }
        public string Standard3 { get; set; }
        public string Standard4 { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Image6 { get; set; }
        public string BasicInfo { get; set; }
        public string DetailInfo { get; set; }
        public string Url { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescriptions { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsOverSales { get; set; }
        public Nullable<bool> IsShowWeb { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public bool IsDelete { get; set; }
        public string SearchText { get; set; }
    }
}
