//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cubetech.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsDefault { get; set; }
        public bool IsDelete { get; set; }
    }
}
